language: java
jdk:
  - oraclejdk8

before_script:
  - echo "Starting build"
script:
  - mvn clean package
  - mvn cobertura:cobertura
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful"
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - echo "Build was failed"

notifications:
  email:
    recipients:
      - CaH4aZzz@gmail.com
      - kosten27@gmail.com
      - artem.sobolenko@gmail.com
      - kjuby009@gmail.com
      - xvanyax2008@gmail.com
      - yurasicv@gmail.com
      - klitsenko.dmitriy@gmail.com
    on_success: never
    on_failure: always