language: java

jdk:
  - oraclejdk8

  cache:
    directories:
      - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success:
  - echo "Build was successful"
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "Build was failed"

notifications:
  email:
    recipients:
      - CaH4aZzz@gmail.com
    on_success: never
    on_failure: always


